# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true
Tags: '/tags/'
tag_page: '/tags/'

Categories: '/categories/'
category_page: '/categories/'

# Setup
title:            Short Notes
tagline:          'on web development'

description:      'Mostly web development'
url:              https://rah00l.github.io
# baseurl:          ''
excerpt_separator: "\n\n"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/rah00l
